services:
  mariadb:
    image: 'mariadb:latest'
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: insecurepassword
      MARIADB_USER: mist
      MARIADB_PASSWORD: changeme
      MARIADB_DATABASE: mistlocation
    volumes:
      - ./data/mariadb:/var/lib/mysql
    healthcheck:
      test: healthcheck.sh --su-mysql --connect --innodb_initialized
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3

  locapid:
    image: 'locapid:latest'
    ports:
      - 18080:18080
    environment:
      - CONFIG_FILE=/app/config/config.json
    volumes:
      - ./data/locapid/:/app/config
    depends_on:
      mariadb:
        condition: service_healthy
      mistpolld:
        condition: service_started

  mistpolld:
    image: 'mistpolld:latest'
    environment:
      - CONFIG_FILE=/app/config/config.json
    volumes:
      - ./data/mistpolld/:/app/config
    depends_on:
      mariadb:
        condition: service_healthy

